[versions]
kotlin = "2.1.10"
compose = "1.5.0"  # Укажите нужную версию для Compose

[plugins]
kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
