[versions]
activity-ktx = "1.6.1"
adapter-rxjava2 = "2.3.0"
adjust-android-webbridge = "4.38.5"
adjust-android = "4.38.5"
af-android-sdk = "6.5.2"
agcp = "1.9.1.303"
android-image-cropper = "2.8.0"
android-sdk-core = "3.5.2"
androidtagview = "v1.1.7"
androidx-room = "2.6.1"
appcompat = "1.6.1"
balloon = "1.3.6"
blurry = "3.0.0"
billing = "7.0.0"
browser = "1.3.0"
circleimageview = "2.2.0"
circularprogressbar-version = "3.1.0"
compiler = "4.16.0"
constraintlayout = "2.1.3"
converter-gson = "2.9.0"
core = "10.0.5"
core-splashscreen = "1.0.1"
dagger = "2.55.0"
dagger-android = "2.55.0"
dagger-android-support = "2.35.1"
daimajia-library-version = "2.1"
datastore-preferences = "1.0.0"
datastore = "1.0.0"
facebook-android-sdk = "16.0.0"
firebase-analytics = "21.2.2"
firebase-config = "21.3.0"
firebase-core = "21.1.1"
firebase-crashlytics = "18.3.6"
firebase-bom = "29.3.1"
firebase-crashlytics-gradle = "3.0.2"
firebase-perf-ktx = "20.3.1"
firebase-dynamic-links = "21.1.0"
firebase-messaging = "23.1.2"
flexbox = "1.0.0"
fragment = "1.3.6"
fragment-ktx = "1.3.6"
google-services = "4.4.2"
gradle = "8.7.3"
gridlayout = "1.0.0"
gson = "2.8.5"
hyperion-shared-preferences = "0.9.34"
hyperion-recorder = "0.9.34"
hyperion-phoenix = "0.9.34"
hyperion-measurement = "0.9.34"
hyperion-disk = "0.9.34"
hyperion-crash = "0.9.34"
hyperion-build-config = "0.9.34"
hyperion-attr = "0.9.34"
hyperion-core = "0.9.34"
installreferrer = "2.2"
jdk9-deps = "1.0"
joda-time = "2.7"
jsr250-api = "1.0"
junit = "4.13.2"
kotlin-android-extensions = "1.9.24"
kotlin-gradle-plugin = "1.6.21"
kotlin-gradle-plugin-version = "2.0.21"
kotlin-reflect = "1.5.31"
kotlinx-coroutines-rx2 = "1.5.2"
kotlinx-coroutines-test = "1.4.1"
kotlinx-datetime = "0.6.0"
leanback = "1.0.0"
library-version = "2.4.0"
lifecycle-common = "2.4.0"
logging-interceptor = "4.10.0"
lottie = "4.2.0"
material = "1.9.0"
media3-exoplayer-hls = "1.4.0"
mobile-sdk = "2.10.1"
mobmetricalib = "5.0.0"
mobmetricapushlib = "2.0.0"
moxy-x = "1.7.0"
moxy-x-androidx = "1.7.0"
moxy-x-compiler = "1.7.0"
multidex = "2.0.1"
multiline-collapsingtoolbar = "27.1.1"
navigation-safe-args-gradle-plugin = "2.8.5"
navigation-ui-ktx = "2.5.3"
nextlib-mediainfo = "0.8.2"
nextlib-media3ext = "0.8.2"
okhttp = "4.11.0"
pageindicatorview = "1.0.1"
paging-rxjava2-ktx = "3.1.1"
paging-runtime-ktx = "3.1.1"
perf-plugin = "1.4.2"
picasso = "2.8"
play-services-ads-identifier = "18.1.0"
play-services-analytics = "18.0.2"
play-services-appset = "16.1.0"
play-services-auth = "20.5.0"
protobuf-gradle-plugin = "0.9.4"
protobuf-javalite = "3.21.11"
r8 = "8.5.35"
retrofit = "2.9.0"
review-ktx = "2.0.1"
review = "2.0.1"
roundcornerprogressbar = "2.0.3"
roundedprogressbar = "3.0.0"
rxandroid = "2.0.2"
rxjava = "2.1.16"
rxrelay = "2.0.0"
stetho = "1.5.1"
support-compat = "28.0.0"
transitionseverywhere = "1.8.0"
volley = "1.2.1"
work-rxjava2 = "2.8.1"
work-runtime-ktx = "2.8.1"
work-runtime = "2.8.1"
zoomlayout = "1.9.0"
tooltip = "release-2.0.5"

[libraries]
adapter-rxjava2 = { module = "com.squareup.retrofit2:adapter-rxjava2", version.ref = "adapter-rxjava2" }
adjust-android = { module = "com.adjust.sdk:adjust-android", version.ref = "adjust-android" }
adjust-android-webbridge = { module = "com.adjust.sdk:adjust-android-webbridge", version.ref = "adjust-android-webbridge" }
af-android-sdk = { module = "com.appsflyer:af-android-sdk", version.ref = "af-android-sdk" }
agcp = { module = "com.huawei.agconnect:agcp", version.ref = "agcp" }
android-image-cropper = { module = "com.theartofdev.edmodo:android-image-cropper", version.ref = "android-image-cropper" }
android-sdk-core = { module = "com.vk:android-sdk-core", version.ref = "android-sdk-core" }
androidtagview = { module = "com.github.whilu:AndroidTagView", version.ref = "androidtagview" }
androidx-activity = { module = "androidx.activity:activity", version.ref = "activity-ktx" }
androidx-activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "activity-ktx" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-browser = { module = "androidx.browser:browser", version.ref = "browser" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
androidx-core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "core-splashscreen" }
androidx-datastore = { module = "androidx.datastore:datastore", version.ref = "datastore" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore-preferences" }
androidx-fragment-ktx = { module = "androidx.fragment:fragment-ktx", version.ref = "fragment-ktx" }
androidx-fragment = { module = "androidx.fragment:fragment", version.ref = "fragment" }
androidx-gridlayout = { module = "androidx.gridlayout:gridlayout", version.ref = "gridlayout" }
androidx-leanback = { module = "androidx.leanback:leanback", version.ref = "leanback" }
androidx-lifecycle-common = { module = "androidx.lifecycle:lifecycle-common", version.ref = "lifecycle-common" }
androidx-lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycle-common" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle-common" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle-common" }
androidx-media3-exoplayer = { module = "androidx.media3:media3-exoplayer", version.ref = "media3-exoplayer-hls" }
androidx-media3-exoplayer-dash = { module = "androidx.media3:media3-exoplayer-dash", version.ref = "media3-exoplayer-hls" }
androidx-media3-exoplayer-hls = { module = "androidx.media3:media3-exoplayer-hls", version.ref = "media3-exoplayer-hls" }
androidx-media3-ui = { module = "androidx.media3:media3-ui", version.ref = "media3-exoplayer-hls" }
androidx-media3-media3-session = { module = "androidx.media3:media3-session", version.ref = "media3-exoplayer-hls" }
androidx-multidex = { module = "androidx.multidex:multidex", version.ref = "multidex" }
androidx-navigation-fragment-ktx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigation-ui-ktx" }
androidx-navigation-safe-args-gradle-plugin = { module = "androidx.navigation:navigation-safe-args-gradle-plugin", version.ref = "navigation-safe-args-gradle-plugin" }
androidx-navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigation-ui-ktx" }
androidx-paging-runtime-ktx = { module = "androidx.paging:paging-runtime-ktx", version.ref = "paging-runtime-ktx" }
androidx-paging-rxjava2-ktx = { module = "androidx.paging:paging-rxjava2-ktx", version.ref = "paging-rxjava2-ktx" }
androidx-room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "androidx-room" }
androidx-room-rxjava2 = { group = "androidx.room", name = "room-rxjava2", version.ref = "androidx-room" }
androidx-room-paging = { group = "androidx.room", name = "room-paging", version.ref = "androidx-room" }
androidx-room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "androidx-room" }
androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "androidx-room" }
androidx-work-runtime = { module = "androidx.work:work-runtime", version.ref = "work-runtime" }
androidx-work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "work-runtime-ktx" }
androidx-work-rxjava2 = { module = "androidx.work:work-rxjava2", version.ref = "work-rxjava2" }
balloon = { module = "com.github.skydoves:balloon", version.ref = "balloon" }
billing = { module = "com.android.billingclient:billing", version.ref = "billing" }
blurry = { module = "jp.wasabeef:blurry", version.ref = "blurry" }
circleimageview = { module = "de.hdodenhof:circleimageview", version.ref = "circleimageview" }
compiler = { module = "com.github.bumptech.glide:compiler", version.ref = "compiler" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "converter-gson" }
core = { module = "com.pierfrancescosoffritti.androidyoutubeplayer:core", version.ref = "core" }
dagger-android-support = { module = "com.google.dagger:dagger-android-support", version.ref = "dagger-android-support" }
dagger-android = { module = "com.google.dagger:dagger-android", version.ref = "dagger-android" }
dagger = { module = "com.google.dagger:dagger", version.ref = "dagger" }
dagger-android-processor = { module = "com.google.dagger:dagger-android-processor", version.ref = "dagger-android" }
dagger-compiler = { module = "com.google.dagger:dagger-compiler", version.ref = "dagger-android" }
daimajia-library = { module = "com.daimajia.easing:library", version.ref = "daimajia-library-version" }
facebook-android-sdk = { module = "com.facebook.android:facebook-android-sdk", version.ref = "facebook-android-sdk" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebase-bom" }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics", version.ref = "firebase-crashlytics" }
firebase-core = { module = "com.google.firebase:firebase-core", version.ref = "firebase-core" }
firebase-config = { module = "com.google.firebase:firebase-config", version.ref = "firebase-config" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics", version.ref = "firebase-analytics" }
firebase-crashlytics-gradle = { module = "com.google.firebase:firebase-crashlytics-gradle", version.ref = "firebase-crashlytics-gradle" }
firebase-messaging = { module = "com.google.firebase:firebase-messaging", version.ref = "firebase-messaging" }
firebase-dynamic-links = { module = "com.google.firebase:firebase-dynamic-links", version.ref = "firebase-dynamic-links" }
firebase-perf-ktx = { module = "com.google.firebase:firebase-perf-ktx", version.ref = "firebase-perf-ktx" }
flexbox = { module = "com.google.android:flexbox", version.ref = "flexbox" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "compiler" }
google-services = { module = "com.google.gms:google-services", version.ref = "google-services" }
gradle = { module = "com.android.tools.build:gradle", version.ref = "gradle" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
hyperion-core = { module = "com.willowtreeapps.hyperion:hyperion-core", version.ref = "hyperion-core" }
hyperion-attr = { module = "com.willowtreeapps.hyperion:hyperion-attr", version.ref = "hyperion-attr" }
hyperion-build-config = { module = "com.willowtreeapps.hyperion:hyperion-build-config", version.ref = "hyperion-build-config" }
hyperion-crash = { module = "com.willowtreeapps.hyperion:hyperion-crash", version.ref = "hyperion-crash" }
hyperion-disk = { module = "com.willowtreeapps.hyperion:hyperion-disk", version.ref = "hyperion-disk" }
hyperion-measurement = { module = "com.willowtreeapps.hyperion:hyperion-measurement", version.ref = "hyperion-measurement" }
hyperion-phoenix = { module = "com.willowtreeapps.hyperion:hyperion-phoenix", version.ref = "hyperion-phoenix" }
hyperion-recorder = { module = "com.willowtreeapps.hyperion:hyperion-recorder", version.ref = "hyperion-recorder" }
hyperion-shared-preferences = { module = "com.willowtreeapps.hyperion:hyperion-shared-preferences", version.ref = "hyperion-shared-preferences" }
installreferrer = { module = "com.android.installreferrer:installreferrer", version.ref = "installreferrer" }
jdk9-deps = { module = "com.github.pengrad:jdk9-deps", version.ref = "jdk9-deps" }
joda-time = { module = "joda-time:joda-time", version.ref = "joda-time" }
jsr250-api = { module = "javax.annotation:jsr250-api", version.ref = "jsr250-api" }
junit = { module = "junit:junit", version.ref = "junit" }
kotlin-android-extensions = { module = "org.jetbrains.kotlin:kotlin-android-extensions", version.ref = "kotlin-android-extensions" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin-gradle-plugin" }
kotlin-gradle-plugin-v1921 = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin-gradle-plugin-version" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin-reflect" }
kotlin-stdlib-jdk7 = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk7", version.ref = "kotlin-gradle-plugin-version" }
kotlinx-coroutines-rx2 = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-rx2", version.ref = "kotlinx-coroutines-rx2" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines-test" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }
logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "logging-interceptor" }
lottie = { module = "com.airbnb.android:lottie", version.ref = "lottie" }
material = { module = "com.google.android.material:material", version.ref = "material" }
mobile-sdk = { module = "cloud.mindbox:mobile-sdk", version.ref = "mobile-sdk" }
mindbox-firebase = { module = "cloud.mindbox:mindbox-firebase" }
mikhaellopez-circularprogressbar = { module = "com.mikhaellopez:circularprogressbar", version.ref = "circularprogressbar-version" }
mobmetricalib = { module = "com.yandex.android:mobmetricalib", version.ref = "mobmetricalib" }
mobmetricapushlib = { module = "com.yandex.android:mobmetricapushlib", version.ref = "mobmetricapushlib" }
moxy-x-androidx = { module = "tech.schoolhelper:moxy-x-androidx", version.ref = "moxy-x-androidx" }
moxy-x = { module = "tech.schoolhelper:moxy-x", version.ref = "moxy-x" }
moxy-x-compiler = { module = "tech.schoolhelper:moxy-x-compiler", version.ref = "moxy-x-compiler" }
multiline-collapsingtoolbar = { module = "net.opacapp:multiline-collapsingtoolbar", version.ref = "multiline-collapsingtoolbar" }
nextlib-media3ext = { module = "com.github.anilbeesetti.nextlib:nextlib-media3ext", version.ref = "nextlib-media3ext" }
nextlib-mediainfo = { module = "com.github.anilbeesetti.nextlib:nextlib-mediainfo", version.ref = "nextlib-mediainfo" }
nineoldandroids-library = { module = "com.nineoldandroids:library", version.ref = "library-version" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
pageindicatorview = { module = "com.romandanylyk:pageindicatorview", version.ref = "pageindicatorview" }
perf-plugin = { module = "com.google.firebase:perf-plugin", version.ref = "perf-plugin" }
picasso = { module = "com.squareup.picasso:picasso", version.ref = "picasso" }
play-services-ads-identifier = { module = "com.google.android.gms:play-services-ads-identifier", version.ref = "play-services-ads-identifier" }
play-services-analytics = { module = "com.google.android.gms:play-services-analytics", version.ref = "play-services-analytics" }
play-services-appset = { module = "com.google.android.gms:play-services-appset", version.ref = "play-services-appset" }
play-services-auth = { module = "com.google.android.gms:play-services-auth", version.ref = "play-services-auth" }
protobuf-gradle-plugin = { module = "com.google.protobuf:protobuf-gradle-plugin", version.ref = "protobuf-gradle-plugin" }
protobuf-javalite = { module = "com.google.protobuf:protobuf-javalite", version.ref = "protobuf-javalite" }
r8 = { module = "com.android.tools:r8", version.ref = "r8" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
review = { module = "com.google.android.play:review", version.ref = "review" }
review-ktx = { module = "com.google.android.play:review-ktx", version.ref = "review-ktx" }
roundcornerprogressbar = { module = "com.akexorcist:RoundCornerProgressBar", version.ref = "roundcornerprogressbar" }
rxrelay = { module = "com.jakewharton.rxrelay2:rxrelay", version.ref = "rxrelay" }
rxjava = { module = "io.reactivex.rxjava2:rxjava", version.ref = "rxjava" }
rxandroid = { module = "io.reactivex.rxjava2:rxandroid", version.ref = "rxandroid" }
stetho = { module = "com.facebook.stetho:stetho", version.ref = "stetho" }
support-compat = { module = "com.android.support:support-compat", version.ref = "support-compat" }
transitionseverywhere = { module = "com.andkulikov:transitionseverywhere", version.ref = "transitionseverywhere" }
volley = { module = "com.android.volley:volley", version.ref = "volley" }
zoomlayout = { module = "com.otaliastudios:zoomlayout", version.ref = "zoomlayout" }
roundedprogressbar = { module = "com.github.MackHartley:RoundedProgressBar", version.ref = "roundedprogressbar" }
tooltip = { group = "com.github.sephiroth74", name = "android-target-tooltip", version.ref = "tooltip"}

[plugins]
